### ISSUE TITLE
Feature request: option to retinafy every image

### ISSUE THREAD

**Issue by bilke** [markgoodyear/craft-retinafy#2] opened 2015-03-16 11:30 UTC
It would be cool to have an option to the `retinafy` twig-filter to process an image without having the `@2x` in its filename.

**Comment by markgoodyear** [comment] 2015-03-16 20:18
There is some downside to 'retinafy' all images, especially when uploading non retina images with no transform applied — it'll create an image twice as small as it was intended. 

I'm not quite sure how to handle this yet, whether it is a global plugin option, or if it is per image, e.g. `{{ image | retinafy('force': true) }}` or similar. Keen to hear your thoughts!

**Comment by bilke** [comment] 2015-03-17 06:08
I would not create a global option due to the reason you told. But on a per image level it would be very useful, e.g. to retinafy picture gallery thumbnails.

**Comment by markgoodyear** [comment] 2015-03-18 10:41
Just thinking about this more, I would say that you can only use force when there is a transform, otherwise there is a risk a user could upload a smaller than required image. At least if it is a transform, it'll always display at the right size, even if the uploaded image is not big enough for 2x.

I can see three options for achieving this:
1. Use `2x` in the transform name — my least favourite.
2. Allow passing in a boolean; `image | retinafy('transformName', true)`.
3. Add a global option to enable retinafy automatically checking if the image is big enough when using a transform.

Implementing both 2 and 3 could also work. What do you think?

**Comment by bilke** [comment] 2015-03-19 08:46
I also like option 2 and 3!

**Comment by markgoodyear** [comment] 2015-03-23 23:51
I've pushed an update to the `develop` branch if you'd like to check it out: https://github.com/markgoodyear/craft-retinafy/tree/develop.

If you head to Plugins, then click on Retinafy, you'll now have some options.

Let me know if you spot any issues, and if not I'll merge into master.

**Comment by bilke** [comment] 2015-03-24 19:35
Works fine! Thank you!

**Comment by markgoodyear** [comment] 2015-03-25 22:28
Awesome! I've merged this to master. I didn't implement option 2 as the global option for transforms is enough I think, keeps it simple :).

**Closed as completed by markgoodyear** 2015-03-25 22:28 UTC
